name: Enhancement Request
description: Suggest an enhancement or new feature
title: "[ENHANCEMENT] "
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Enhancement Description
      description: A clear and concise description of the enhancement you're proposing
      placeholder: Describe the enhancement...
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case / Problem
      description: What problem does this enhancement solve? What's the use case?
      placeholder: Explain the problem this enhancement would solve...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented
      placeholder: How would you like this to work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: What alternatives have you considered?
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the enhancement
      placeholder: Any additional information that might help...
    validations:
      required: false