name: Add issues to project

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'bug') || contains(github.event.issue.labels.*.name, 'enhancement')
    steps:
      - name: Add to project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/Software-by-Quokka-org/projects/9
          github-token: ${{ secrets.GITHUB_TOKEN }}
          project-id: PVT_kwDOCCJDsc4A7yNy